[package]
name = "rhymix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmudict-fast = "0.8.0"
actix-web = "4.3.0"
